//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace WebApplication1.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SampleDbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SampleDbEntities object using the connection string found in the 'SampleDbEntities' section of the application configuration file.
        /// </summary>
        public SampleDbEntities() : base("name=SampleDbEntities", "SampleDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SampleDbEntities object.
        /// </summary>
        public SampleDbEntities(string connectionString) : base(connectionString, "SampleDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SampleDbEntities object.
        /// </summary>
        public SampleDbEntities(EntityConnection connection) : base(connection, "SampleDbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tbusr> tbusrs
        {
            get
            {
                if ((_tbusrs == null))
                {
                    _tbusrs = base.CreateObjectSet<tbusr>("tbusrs");
                }
                return _tbusrs;
            }
        }
        private ObjectSet<tbusr> _tbusrs;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tbusrs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotbusrs(tbusr tbusr)
        {
            base.AddObject("tbusrs", tbusr);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SampleDbModel", Name="tbusr")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tbusr : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tbusr object.
        /// </summary>
        /// <param name="usrcod">Initial value of the usrcod property.</param>
        public static tbusr Createtbusr(global::System.Int32 usrcod)
        {
            tbusr tbusr = new tbusr();
            tbusr.usrcod = usrcod;
            return tbusr;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 usrcod
        {
            get
            {
                return _usrcod;
            }
            set
            {
                if (_usrcod != value)
                {
                    OnusrcodChanging(value);
                    ReportPropertyChanging("usrcod");
                    _usrcod = StructuralObject.SetValidValue(value, "usrcod");
                    ReportPropertyChanged("usrcod");
                    OnusrcodChanged();
                }
            }
        }
        private global::System.Int32 _usrcod;
        partial void OnusrcodChanging(global::System.Int32 value);
        partial void OnusrcodChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usrnam
        {
            get
            {
                return _usrnam;
            }
            set
            {
                OnusrnamChanging(value);
                ReportPropertyChanging("usrnam");
                _usrnam = StructuralObject.SetValidValue(value, true, "usrnam");
                ReportPropertyChanged("usrnam");
                OnusrnamChanged();
            }
        }
        private global::System.String _usrnam;
        partial void OnusrnamChanging(global::System.String value);
        partial void OnusrnamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usrunm
        {
            get
            {
                return _usrunm;
            }
            set
            {
                OnusrunmChanging(value);
                ReportPropertyChanging("usrunm");
                _usrunm = StructuralObject.SetValidValue(value, true, "usrunm");
                ReportPropertyChanged("usrunm");
                OnusrunmChanged();
            }
        }
        private global::System.String _usrunm;
        partial void OnusrunmChanging(global::System.String value);
        partial void OnusrunmChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usrpwd
        {
            get
            {
                return _usrpwd;
            }
            set
            {
                OnusrpwdChanging(value);
                ReportPropertyChanging("usrpwd");
                _usrpwd = StructuralObject.SetValidValue(value, true, "usrpwd");
                ReportPropertyChanged("usrpwd");
                OnusrpwdChanged();
            }
        }
        private global::System.String _usrpwd;
        partial void OnusrpwdChanging(global::System.String value);
        partial void OnusrpwdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usreml
        {
            get
            {
                return _usreml;
            }
            set
            {
                OnusremlChanging(value);
                ReportPropertyChanging("usreml");
                _usreml = StructuralObject.SetValidValue(value, true, "usreml");
                ReportPropertyChanged("usreml");
                OnusremlChanged();
            }
        }
        private global::System.String _usreml;
        partial void OnusremlChanging(global::System.String value);
        partial void OnusremlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> usrmob
        {
            get
            {
                return _usrmob;
            }
            set
            {
                OnusrmobChanging(value);
                ReportPropertyChanging("usrmob");
                _usrmob = StructuralObject.SetValidValue(value, "usrmob");
                ReportPropertyChanged("usrmob");
                OnusrmobChanged();
            }
        }
        private Nullable<global::System.Int32> _usrmob;
        partial void OnusrmobChanging(Nullable<global::System.Int32> value);
        partial void OnusrmobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usrrol
        {
            get
            {
                return _usrrol;
            }
            set
            {
                OnusrrolChanging(value);
                ReportPropertyChanging("usrrol");
                _usrrol = StructuralObject.SetValidValue(value, true, "usrrol");
                ReportPropertyChanged("usrrol");
                OnusrrolChanged();
            }
        }
        private global::System.String _usrrol;
        partial void OnusrrolChanging(global::System.String value);
        partial void OnusrrolChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> usrcdt
        {
            get
            {
                return _usrcdt;
            }
            set
            {
                OnusrcdtChanging(value);
                ReportPropertyChanging("usrcdt");
                _usrcdt = StructuralObject.SetValidValue(value, "usrcdt");
                ReportPropertyChanged("usrcdt");
                OnusrcdtChanged();
            }
        }
        private Nullable<global::System.DateTime> _usrcdt;
        partial void OnusrcdtChanging(Nullable<global::System.DateTime> value);
        partial void OnusrcdtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usrisdel
        {
            get
            {
                return _usrisdel;
            }
            set
            {
                OnusrisdelChanging(value);
                ReportPropertyChanging("usrisdel");
                _usrisdel = StructuralObject.SetValidValue(value, true, "usrisdel");
                ReportPropertyChanged("usrisdel");
                OnusrisdelChanged();
            }
        }
        private global::System.String _usrisdel;
        partial void OnusrisdelChanging(global::System.String value);
        partial void OnusrisdelChanged();

        #endregion

    }

    #endregion

}
