//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbusr
    {
        public int usrcod { get; set; }
        [Required]
        public string usrnam { get; set; }
        public string usrunm { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public string usrpwd { get; set; }
        public string usreml { get; set; }
        public Nullable<int> usrmob { get; set; }
        public string usrrol { get; set; }
        public Nullable<System.DateTime> usrcdt { get; set; }
        public string usrisdel { get; set; }
    }
}
