//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ddc1Entities1 : DbContext
    {
        public ddc1Entities1()
            : base("name=ddc1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_candidate> Tb_candidate { get; set; }
    
        public virtual ObjectResult<getapplicationcountdata_Result1> getapplicationcountdata()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getapplicationcountdata_Result1>("getapplicationcountdata");
        }
    }
}
