//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_candidate
    {
        public int ID { get; set; }
        public string Reg_for { get; set; }
        public string eml { get; set; }
        public string Mob { get; set; }
        public string Appl_nam { get; set; }
        public string Appl_fath_nam { get; set; }
        public string app_mothr_nam { get; set; }
        public string gender { get; set; }
        public string Merit_status { get; set; }
        public string hsbnd_nam { get; set; }
        public string dob { get; set; }
        public string birth_plc { get; set; }
        public string nation { get; set; }
        public string othr_nation { get; set; }
        public string res_add { get; set; }
        public string res_cors_add { get; set; }
        public string cty { get; set; }
        public string dist { get; set; }
        public Nullable<int> pin_cod { get; set; }
        public string mat_crs_nam { get; set; }
        public string mat_bord_nam { get; set; }
        public string mat_colg_schol { get; set; }
        public string mat_adm_yr { get; set; }
        public string mat_pass_yr { get; set; }
        public Nullable<int> mat_obt_mark { get; set; }
        public Nullable<int> mat_total_mark { get; set; }
        public Nullable<double> mat_percentage { get; set; }
        public string reg_no_pnrc { get; set; }
        public string mid_reg_no { get; set; }
        public string reg_dat_pnrc { get; set; }
        public string high_crs_nam { get; set; }
        public string high_bord_nam { get; set; }
        public string high_colg_school { get; set; }
        public string high_adm_yr { get; set; }
        public string high_pass_yr { get; set; }
        public string high_trng_comp_on { get; set; }
        public Nullable<int> high_obt_mark { get; set; }
        public Nullable<int> high_total_mark { get; set; }
        public Nullable<double> high_percentage { get; set; }
        public string high_speclization { get; set; }
        public string first_trng_place { get; set; }
        public string first_trng_frm { get; set; }
        public string first_trng_to { get; set; }
        public string sec_trng_place { get; set; }
        public string sec_trng_frm { get; set; }
        public string sec_trng_to { get; set; }
        public string thrd_trng_place { get; set; }
        public string thrd_trng_frm { get; set; }
        public string thrd_trng_to { get; set; }
        public string trng_duratin { get; set; }
        public string rsn_gap { get; set; }
        public string reg_type { get; set; }
        public string parnt_state { get; set; }
        public string noc_cert { get; set; }
        public Nullable<System.DateTime> appointment { get; set; }
        public string tym_slot { get; set; }
        public string pay_mode { get; set; }
        public string ammount { get; set; }
        public string pay_status { get; set; }
        public string sr_no { get; set; }
        public string midwifery_reg_no { get; set; }
        public string nurse_reg_no { get; set; }
        public Nullable<System.DateTime> date_of_app { get; set; }
        public Nullable<System.DateTime> date_of_reg { get; set; }
        public Nullable<System.DateTime> date_of_exp { get; set; }
        public Nullable<System.DateTime> certificate_issue_date { get; set; }
        public string udf1_v { get; set; }
        public string udf2_v { get; set; }
        public string udf3_v { get; set; }
        public Nullable<System.DateTime> perm_appointment { get; set; }
        public string perm_tymslot { get; set; }
        public string udf5_v { get; set; }
        public string udf6_v { get; set; }
        public Nullable<int> udf3_int { get; set; }
        public Nullable<int> udf4_int { get; set; }
        public string udf5_dat { get; set; }
        public Nullable<System.DateTime> udf6_dat { get; set; }
        public string crs3nam { get; set; }
        public string crs3unvnam { get; set; }
        public string crs3passyr { get; set; }
        public string crs3specialization { get; set; }
        public string udf1 { get; set; }
        public string udf2 { get; set; }
        public string udf3 { get; set; }
        public Nullable<System.DateTime> udf4 { get; set; }
    }
}
