//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbdoc
    {
        public long doccod { get; set; }
        public string docregnum { get; set; }
        public string doctit { get; set; }
        public string docfnm { get; set; }
        public string doclnm { get; set; }
        public string docfatfnm { get; set; }
        public string docfatlnm { get; set; }
        public string docdob { get; set; }
        public string docbirpla { get; set; }
        public string docetv { get; set; }
        public string docgen { get; set; }
        public string docnat { get; set; }
        public string docrescty { get; set; }
        public string docresctytyp { get; set; }
        public string docresadd { get; set; }
        public Nullable<long> docrestel { get; set; }
        public Nullable<int> docrespin { get; set; }
        public string docressta { get; set; }
        public string docrescou { get; set; }
        public string docprocty { get; set; }
        public string docproctytyp { get; set; }
        public string docproadd { get; set; }
        public Nullable<long> docprotel { get; set; }
        public Nullable<int> docpropin { get; set; }
        public string docprosta { get; set; }
        public string docprocou { get; set; }
        public string doceml { get; set; }
        public string docpwd { get; set; }
        public string docmob { get; set; }
        public string docsig { get; set; }
        public string docimg { get; set; }
        public string docfin { get; set; }
        public string doceye { get; set; }
        public string docmir { get; set; }
        public string docdeg1 { get; set; }
        public string docuni1 { get; set; }
        public Nullable<int> docyop1 { get; set; }
        public string docdeg2 { get; set; }
        public string docuni2 { get; set; }
        public Nullable<int> docyop2 { get; set; }
        public string docdeg3 { get; set; }
        public string docuni3 { get; set; }
        public Nullable<int> docyop3 { get; set; }
        public string docsta { get; set; }
        public Nullable<System.DateTime> doccdt { get; set; }
        public Nullable<System.DateTime> docudt { get; set; }
        public string docisdel { get; set; }
    }
}
